### ISSUE TITLE
Library dependencies

### ISSUE THREAD

**Issue by sandeshlasnapure** [aryarohit07/GlideFaceDetectionTransformation#1]
What is the use of play-services? Because it will increase the apk size.

**Comment by aryarohit07** [comment]
@sandeshlasnapure , It uses Google Play's Mobile Vision API to detect faces in the bitmap. And yes, it will increase apk size but it is using only Mobile Vision API, not the entire package.
BTW I am planning to release a new version of the library where, in case, you have performed face detection on the server, you may skip Mobile Vision API.

**Comment by sandeshlasnapure** [comment]
That would be great. Waiting for next release.
