### ISSUE TITLE
Throws RuntimeExeption: Initialize GlideFaceDetector 

### ISSUE THREAD

**Issue by ghost** [aryarohit07/GlideFaceDetectionTransformation#3]
I have  `GlideFaceDetector.initialize(context)` in the `onCreate()`. when opening an activity and coming back to the one using `GlideFaceDetecor` inside a `RecyclerView`, when scrolled, results in a crash with the above message.

**Comment by aryarohit07** [comment]
If you have got RuntimeException with this message `Initialize GlideFaceDetector by calling GlideFaceDetector.initialize(context).`, it means you have not initialized the `GlideFaceDetector` before calling `FaceCenterCrop()`.

Also, if you have released the detector by calling `GlideFaceDetector.releaseDetector();` then you will have to re-initialize the detector.

Please add some code for better debugging the problem.

**Comment by ghost** [comment]
I have a `recyclerView` which loads images with glide. I have initialized `GlideFaceDetector` in my `onCreate()` method. Released it in the `onDestroy()` method and no where else. The exception occurs only when i open a detail of the image and close it and try to scroll the `recyclerView` again.

I have even tried calling  `GlideFaceDetector.initialize(context)` inside `onResume()` method. But still the same error. Its a common setup with a `recyclerView` and `ListViewHolder` to open up an activity on click. Nothing extra in the code to be shared here.

**Comment by aryarohit07** [comment]
Are you using the` recyclerView` inside a `fragment`? And is the **detail of the image** also a `fragment`?

**Comment by ghost** [comment]
It is a single `activity` without `fragments` anywhere in it. The activity houses the `recyclerView` and the `recyclerView` uses a normal view which has this image and a `textview`. **Typical setup**. 

**There is no issue with launching this `activity` with the `recyclerView` using `FaceCenterCrop` for the first time**. It only happens when you start another `activity` from it and return back to it and scroll the `recyclerView` which causes the `onBindViewHolder` to call `Glide` to load the next image to the `viewHolder` which causes the crash since the `FaceCenterCrop() Transformation` does not seem to keep the `GlideFaceDetector.initialize(context)` alive between **activity switches**. That will be my guess to whats happening here. 

And Thanks for your quick replies Rohit.

**Comment by aryarohit07** [comment]
Are you releasing the detector in the **image detail (second)** activity? If yes, then that might be the cause of the crash because `GlideFaceDetector` maintains a singleton instance and you should release the detector only when you are done with it. Else you will have to re-initialize the `GlideFaceDetector` to use again.

**Comment by ghost** [comment]
Thanks Rohit. That seems to solve the problem. 
But it gets hard to maintain this behaviour when you have to check whether to release the `GlideFaceDetector` or not in that activity as it could be called from many places within the app wherein I may not be initializing `GlideFaceDetector` in the activity that calls this **detail activity**. But anyway some `extras` with the `intent` passed to open the detail activity should work for now.
 
Kudos!

**Comment by aryarohit07** [comment]
Yes @jishincreo , I agree with you.

Just treat the `GlideFaceDetector` as a singleton instance (which actually is right now). Will try to improve it's lifecycle in further releases.
